import = [
    "~/.config/alacritty/themes/themes/onedark.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 0.8
dynamic_padding = false
option_as_alt = "Both"

  [window.padding]
  x = 10
  y = 10

  [window.dimensions]
  columns = 180
  lines = 50

  [window.position]
  x = 268
  y = 268

[font]
size = 14

  [font.normal]
  family = "GeistMono Nerd Font"
  style = "Medium"

  [font.italic]
  family = "GeistMono Nerd Font"
  style = "Medium Italic"

  [font.bold]
  family = "GeistMono Nerd Font"
  style = "Heavy"

  [font.bold_italic]
  family = "GeistMono Nerd Font"
  style = "Heavy Italic"
