import = [
    "~/.config/alacritty/themes/themes/onedark.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 0.8
dynamic_padding = false

  [window.padding]
  x = 14
  y = 10

[font]
size = 14

  [font.normal]
  family = "SFMono Nerd Font"
  style = "Medium"

  [font.italic]
  family = "SFMono Nerd Font"
  style = "Medium Italic"

  [font.bold]
  family = "SFMono Nerd Font"
  style = "Heavy"

  [font.bold_italic]
  family = "SFMono Nerd Font"
  style = "Heavy Italic"
